package com.progressly.activity.api;
import com.progressly.activity.domain.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class TaskService { final TaskRepository tasks; public TaskService(TaskRepository t){tasks=t;}
 @Transactional public TaskDtos.Response create(UUID u,TaskDtos.Request r){return out(tasks.save(new Task(u,r.title().trim(),r.description(),r.category(),r.priority(),r.dueDate(),r.dueTime(),r.estimatedMinutes(),r.goalId(),r.milestoneId(),r.recurrence())));}
 @Transactional(readOnly=true) public Page<TaskDtos.Response> list(UUID u,Pageable p){return tasks.findByUserId(u,p).map(this::out);} @Transactional(readOnly=true) public TaskDtos.Response get(UUID u,UUID id){return out(find(u,id));}
 @Transactional public TaskDtos.Response update(UUID u,UUID id,TaskDtos.Request r){Task t=find(u,id);t.update(r.title().trim(),r.description(),r.category(),r.priority(),r.dueDate(),r.dueTime(),r.estimatedMinutes(),r.actualMinutes(),r.goalId(),r.milestoneId(),r.recurrence()==null?Task.Recurrence.NONE:r.recurrence(),r.status()==null?t.getStatus():r.status());return out(tasks.save(t));}
 @Transactional public TaskDtos.Response status(UUID u,UUID id,Task.Status s){Task t=find(u,id);t.status(s);return out(tasks.save(t));} @Transactional public void delete(UUID u,UUID id){tasks.delete(find(u,id));}
 private Task find(UUID u,UUID id){return tasks.findByIdAndUserId(id,u).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Task not found"));} private TaskDtos.Response out(Task t){return new TaskDtos.Response(t.getId(),t.getTitle(),t.getDescription(),t.getCategory(),t.getPriority(),t.getDueDate(),t.getDueTime(),t.getEstimatedMinutes(),t.getActualMinutes(),t.getGoalId(),t.getMilestoneId(),t.getRecurrence(),t.getStatus(),t.getCreatedAt(),t.getUpdatedAt());}
}
