package com.progressly.goal.api;
import com.progressly.goal.domain.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class GoalService { private final GoalRepository goals; private final MilestoneRepository milestones;
 public GoalService(GoalRepository goals,MilestoneRepository milestones){this.goals=goals;this.milestones=milestones;}
 @Transactional public GoalDtos.GoalResponse create(UUID user,GoalDtos.GoalRequest r){return response(goals.save(new Goal(user,r.title().trim(),r.description(),r.category(),r.trackingType(),r.targetValue(),r.startDate(),r.targetDate(),r.priority())));}
 @Transactional(readOnly=true) public Page<GoalDtos.GoalResponse> list(UUID user,Pageable p){return goals.findByUserId(user,p).map(this::response);}
 @Transactional(readOnly=true) public GoalDtos.GoalResponse get(UUID user,UUID id){return response(find(user,id));}
 @Transactional public GoalDtos.GoalResponse update(UUID user,UUID id,GoalDtos.GoalRequest r){Goal g=find(user,id);g.update(r.title().trim(),r.description(),r.category(),r.trackingType(),r.targetValue(),r.startDate(),r.targetDate(),r.priority(),r.status()==null?g.getStatus():r.status());return response(goals.save(g));}
 @Transactional public void delete(UUID user,UUID id){Goal g=find(user,id); goals.delete(g);}
 @Transactional public GoalDtos.GoalResponse progress(UUID user,UUID id,GoalDtos.ProgressRequest r){Goal g=find(user,id);g.progress(r.currentValue());return response(goals.save(g));}
 @Transactional public GoalDtos.MilestoneResponse addMilestone(UUID user,UUID goalId,GoalDtos.MilestoneRequest r){find(user,goalId);int order=r.sortOrder()==null?milestones.findByGoalIdAndUserIdOrderBySortOrderAsc(goalId,user).size():r.sortOrder();return milestone(milestones.save(new Milestone(goalId,user,r.title().trim(),r.description(),order)));}
 @Transactional(readOnly=true) public List<GoalDtos.MilestoneResponse> milestones(UUID user,UUID goalId){find(user,goalId);return milestones.findByGoalIdAndUserIdOrderBySortOrderAsc(goalId,user).stream().map(this::milestone).toList();}
 @Transactional public GoalDtos.MilestoneResponse updateMilestone(UUID user,UUID goalId,UUID id,GoalDtos.MilestoneRequest r){Milestone m=findMilestone(user,goalId,id);m.update(r.title().trim(),r.description(),r.sortOrder()==null?m.getSortOrder():r.sortOrder());return milestone(milestones.save(m));}
 @Transactional public GoalDtos.MilestoneResponse completeMilestone(UUID user,UUID goalId,UUID id,boolean completed){Milestone m=findMilestone(user,goalId,id);m.completed(completed);return milestone(milestones.save(m));}
 @Transactional public void deleteMilestone(UUID user,UUID goalId,UUID id){milestones.delete(findMilestone(user,goalId,id));}
 private Goal find(UUID u,UUID id){return goals.findByIdAndUserId(id,u).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Goal not found"));} private Milestone findMilestone(UUID u,UUID g,UUID id){return milestones.findByIdAndGoalIdAndUserId(id,g,u).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Milestone not found"));}
 private GoalDtos.GoalResponse response(Goal g){return new GoalDtos.GoalResponse(g.getId(),g.getTitle(),g.getDescription(),g.getCategory(),g.getTrackingType(),g.getTargetValue(),g.getCurrentValue(),g.getStartDate(),g.getTargetDate(),g.getPriority(),g.getStatus(),g.getCreatedAt(),g.getUpdatedAt());} private GoalDtos.MilestoneResponse milestone(Milestone m){return new GoalDtos.MilestoneResponse(m.getId(),m.getGoalId(),m.getTitle(),m.getDescription(),m.getSortOrder(),m.isCompleted());}
}
